// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixgfwdseslkirxtwooib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Z2Z3ZHNlc2xraXJ4dHdvb2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzgzNDUsImV4cCI6MjA2NTU1NDM0NX0.Brz0k08xZqknszvXjJi3ua2RT25W_6PP_GBdRqhbfRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);